/// Flutter icons Svg
/// Copyright (C) 2024 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Svg
///      fonts:
///       - asset: fonts/Svg.ttf
///
///
///
library;

import 'package:flutter/material.dart';

class Svg {
  Svg._();

  static const _kFontFam = 'Svg';
  static const String? _kFontPkg = null;

  static const IconData empty =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cart =
      IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  // ignore: constant_identifier_names
  static const IconData location_outline =
      IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fire =
      IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Returns a [Icon] widget that displays an [IconData].
  /// Uses color from [textTheme.bodyMedium] for consistance looking with texts.
  static Icon textIcon(
    BuildContext context, {
    IconData icon = empty,
    double size = 24,
  }) {
    return Icon(icon,
        size: size,
        color: Theme.of(context).textTheme.copyWith().bodyMedium?.color);
  }
}
